### ISSUE TITLE
CSS Grid

### ISSUE THREAD

**Issue by tomptrs** [MattZK/ProjectZeppelin#17]
suggestie voor CSS Grid:
Werken met  grid-template-areas : 

           .container{
                display:grid;
               grid-gap: 20px;
                 grid-template-columns: 1fr 1fr;
                grid-template-rows:1fr 2fr 2fr;
              grid-template-areas: 
                  "hoofding hoofding"
                    "sectie1 sectie2"
                  "sectie3 sectie4";
            }
            .container .hoofding{
                grid-area: hoofding;
            }
            .container .sectie1{
               grid-area: sectie1;
            }
            .container .sectie2{
                grid-area: sectie2;
            }
            .container .sectie3{
                grid-area: sectie3;
            }
            .container .sectie4{
                grid-area: sectie4;
            }

=> werken met verschillende schermen wordt dan zeer eenvoudig:

  @media (min-width:1000px){
             .container{
                grid-gap: 20px;
                grid-template-columns: 1fr 1fr 1fr 1fr;
                grid-template-rows:1fr 2fr;
                grid-template-areas: 
                  "hoofding hoofding hoofding hoofding"
                    "sectie1 sectie2 sectie3 sectie4";

            }
        }

**Comment by MattZK** [comment]
Code toegevoegd, bedankt voor het openen van deze issue.
